/* Compile src/*.jsx -> app.js (JSX only, no polyfills, no bundling).
 *
 *   npm install && npm run build
 *
 * Every file in src/ is a fragment of ONE classic script, not a module.
 * They share a single top-level scope, so there are no imports and no
 * exports anywhere. index.html loads app.js with a plain <script> tag,
 * and that is what lets the page run straight off the filesystem: ES
 * modules are blocked by CORS over file://, a bundler would need a
 * toolchain, and both would cost the "just open index.html" promise.
 *
 * SOURCES below is therefore load-bearing — it is the file order, and the
 * file order is the dependency order. Anything evaluated at load time (a
 * const initialiser, an object literal) must come after what it reads.
 * Function declarations, and anything referenced only from inside a
 * function body, can sit anywhere. mount.jsx renders the app, so it is
 * always last.
 *
 * app.js is committed so the page works from a bare checkout and from
 * GitHub Pages with no build step. CI never rebuilds it, so a change to
 * src/ has to be built and committed together with its output.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { transformAsync } from '@babel/core';
import presetReact from '@babel/preset-react';

/* Fingerprint of the sources, stamped into app.js and re-checked by the test
   suite, which is the only thing CI runs. Without it, editing src/ and
   forgetting to rebuild would deploy the previous engine and every test would
   still pass, because the tests load app.js.
   Sorted by name so both sides compute it the same way with no shared state,
   and newline-normalised so it survives a checkout under core.autocrlf --
   hashing raw bytes would fail on every Windows clone. */
export function fingerprint(dir){
  const h = crypto.createHash('sha256');
  for(const name of fs.readdirSync(dir).filter(f=>f.endsWith('.jsx')).sort())
    h.update(name).update('\0')
     .update(fs.readFileSync(path.join(dir,name),'utf8').replace(/\r\n/g,'\n'))
     .update('\0');
  return h.digest('hex').slice(0,16);
}

const SOURCES = [
  'constants.jsx',       // timings, node model, log helpers, colour scales
  'raft-engine.jsx',     // elections, replication, RPC delivery, tick
  'raft-scenarios.jsx',  // makeWorld, membership, SCENARIOS
  'txn-engine.jsx',      // two-phase commit over the engine above
  'txn-scenarios.jsx',   // TXN_SCENARIOS
  'layout.jsx',          // single-cluster ring geometry
  'explain.jsx',         // live narration for both views
  'app.jsx',             // root component, controls, page layout
  'stage.jsx',           // cluster SVG + the wire/message drawing both stages share
  'txn-stage.jsx',       // 2PC SVG: groups, small nodes, cross-group RPCs
  'panels.jsx',          // side panels and the tooltip
  'mount.jsx',           // renders <App/> — must stay last
];

const here = path.dirname(fileURLToPath(import.meta.url));
const out = [];

for (const name of SOURCES) {
  const file = path.join(here, 'src', name);
  const src = fs.readFileSync(file, 'utf8');

  // Guard the contract above: one import would silently break file://.
  if (/^\s*(import|export)\s/m.test(src))
    throw new Error(`src/${name} uses import/export — files in src/ are fragments of a single ` +
                    `classic script, not modules. Add the file to SOURCES instead.`);

  const { code } = await transformAsync(src, {
    presets: [[presetReact, { runtime: 'classic' }]],
    babelrc: false,
    configFile: false,
    compact: false,
    filename: file,          // so syntax errors name the file they came from
  });
  out.push(`/* ==== src/${name} ${'='.repeat(Math.max(4, 54 - name.length))} */\n${code.trim()}`);
}

const stamp = fingerprint(path.join(here, 'src'));
const bundle = `/* GENERATED by build.mjs from src/ — do not edit this file.\n`
             + ` * src-fingerprint: ${stamp}\n`
             + ` * Run \`npm run build\` after changing anything in src/, and commit both.\n */\n\n`
             + out.join('\n\n') + '\n';
fs.writeFileSync(path.join(here, 'app.js'), bundle);
console.log(`app.js written — ${SOURCES.length} sources, ${bundle.length} chars, fingerprint ${stamp}`);
